# code: language=ansible
---
- name: Install kubernetes (admin)
  become: true
  ansible.builtin.apt:
    name:
      - kubelet
      - kubectl
      - kubeadm
      - kubernetes-cni
    state: present
  when: kubernetes_node_type == 'admin'
