---
- name: assert kubernetes_node_type
  assert:
    that:
      - kubernetes_node_type in kubernetes_supported_node_type

- name: install dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Create APT keyrings dir
  become: yes
  file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'

- name: add kubernetes key
  become: yes
  get_url:
    url: 'https://dl.k8s.io/apt/doc/apt-key.gpg'
    dest: '/etc/apt/keyrings/kubernetes-archive-keyring.gpg'
    mode: 'u=rw,go=r'
    force: yes

- name: remove old kubernetes repo
  become: yes
  apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/cloud.google.gpg]
      http://apt.kubernetes.io/ kubernetes-xenial main
    state: absent

- name: add kubernetes repo
  become: yes
  apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg]
      http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- include_tasks: '{{ kubernetes_node_type }}.yml'
