---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-kubernetes-ubuntu-min
    image: ubuntu:16.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: master-ubuntu-min

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
