---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  roles:
    - role: ansible-role-kubernetes
      # Can't test admin/development as kubeadm requires systemd to install
      kubernetes_node_type: master
