---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-kubernetes-controller-ubuntu-max
    image: ubuntu:18.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../controller/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: controller-ubuntu-min

verifier:
  name: testinfra
  directory: ../controller/tests
  lint:
    name: flake8
